### ISSUE TITLE
[FE/feat] Nav, Header 구현, Test Components 연결

### ISSUE THREAD

**Issue by xxyeon129** [OurPortfolio/FE#19]
## Description
- Nav, Header 구현
- Test Components 연결
## Todo
1. [x] Nav 각 버튼 클릭 시 카테고리 변경 반영
2. [x] Nav 로그아웃 구현
3. [x] Nav User Profile 구현
4. [x] Nav figma UI 퍼블리싱
5. [x] Header figma UI 퍼블리싱
6. [x] Header 각 버튼 클릭 시 이동 구현
7. [x] Test처리된 컴포넌트 병합/연동

## Duration
1-2d (~6/5)
