### ISSUE TITLE
[FE/style] 메인 페이지/포트폴리오 작성 페이지/마이 포트폴리오 페이지 UI 구현, 포트폴리오 작성 페이지 기능 구체화

### ISSUE THREAD

**Issue by xxyeon129** [OurPortfolio/FE#21]
## Description
#20 메인 페이지 UI
포트폴리오 작성 페이지 UI
마이 포트폴리오 페이지 UI
## Todo
1. [x] 메인 페이지 UI
2. [x] 포트폴리오 작성 페이지 유효성검사 필수입력 추가수정
3. [x] 포트폴리오 작성 페이지 UI 조정
4. [x] 마이 포트폴리오 페이지 UI

## Duration
1-2d(6/6)
