### ISSUE TITLE
[FE/feat] 메인 페이지 기능구현

### ISSUE THREAD

**Issue by xxyeon129** [OurPortfolio/FE#3]
## Description
#11 메인 페이지 기능 구현

## Todo
1. [x] 무한 스크롤 구현
2. [x] 직종 카테고리 필터링 구현
3. [x] 직무 필터링 구현
4. [x] 필터링 에러 핸들링
5. [x]  코드 리팩토링
6. [x] 새로고침 시 직무 필터링 유지

## Duration
1d (~5/29)
