### ISSUE TITLE
[FE/style] figma 리디자인 UI 반영

### ISSUE THREAD

**Issue by xxyeon129** [OurPortfolio/FE#45]
## Description
#44  figma 리디자인 UI 전체 반영
## Todo
1. [x] 메인 페이지 UI
2. [x] Header UI
3. [x] Nav UI
4. [x] 홈페이지 UI
5. [x] 포트폴리오 등록 페이지 각 단계 UI
6. [x] 마이 포트폴리오 페이지 UI

## Duration
1-2d
