### ISSUE TITLE
[FE/style] UI 전반 반응형 구현

### ISSUE THREAD

**Issue by xxyeon129** [OurPortfolio/FE#46]
## Description
UI 전반 반응형 구현
## Todo
1. [x] Header
2. [x] Nav
3. [x] 메인 페이지 필터
4. [x] 메인 페이지 Nav 카테고리 필터
5. [x] 포트폴리오 작성 페이지 각 단계
6. [x] 마이 포트폴리오 페이지
7. [x] 홈페이지

## Duration
1-2d
